Repository Financial-Instruments-Mini/Project_BE, pull requests merged in 2023-02, with the labels that each got.

#22 [fix] entity 요청사항 변경
  src/main/java/com/financial/apply/controller/ApplyController.java
  src/main/java/com/financial/apply/service/ApplyService.java
  src/main/java/com/financial/bookmark/controller/BookmarkController.java
  src/main/java/com/financial/bookmark/service/BookmarkService.java
  src/main/java/com/financial/interest/controller/InterestController.java
  src/main/java/com/financial/interest/entity/Interest.java
  src/main/java/com/financial/interest/repository/InterestRepository.java
  src/main/java/com/financial/interest/service/InterestService.java
  src/main/java/com/financial/member/controller/MemberController.java
  src/main/java/com/financial/member/service/MemberService.java
  src/main/java/com/financial/product/controller/ProductController.java
  src/main/java/com/financial/product/entity/Deposit.java
  src/main/java/com/financial/product/entity/Product.java
  src/main/java/com/financial/product/entity/Saving.java
  src/main/java/com/financial/product/entity/enums/Keyword.java
  src/main/java/com/financial/product/service/ProductService.java
Labels: Status: Available, Priority: High, For: Backend

#26 #25 [feat]장바구니 등록
  src/main/java/com/financial/apply/controller/ApplyController.java
  src/main/java/com/financial/apply/dto/ApplyRegistrationReq.java
  src/main/java/com/financial/apply/entity/Apply.java
  src/main/java/com/financial/apply/service/ApplyService.java
Labels: Status: Available, For: Backend, For: API

#33 #30 상품 조회 상세 페이지
  src/main/java/com/financial/interest/dto/InterestResponseDTO.java
  src/main/java/com/financial/product/controller/ProductController.java
  src/main/java/com/financial/product/dto/ProductDetailResponseDTO.java
  src/main/java/com/financial/product/service/ProductService.java
Labels: Status: Completed, Priority: Medium, For: API

#42 #40 신청해지
  src/main/java/com/financial/apply/controller/ApplyController.java
  src/main/java/com/financial/apply/service/ApplyService.java
Labels: For: Backend, For: API

#60 #59 [fix] api 출력 스펙 변경
  src/main/java/com/financial/interest/dto/InterestByAll.java
Labels: Status: Completed, Priority: Critical, For: Backend, For: API

#74 docs: #73 swagger api 작성
  src/main/java/com/financial/apply/controller/ApplyController.java
  src/main/java/com/financial/apply/dto/ApplyRegistrationReq.java
  src/main/java/com/financial/bookmark/controller/BookmarkController.java
  src/main/java/com/financial/bookmark/dto/BookmarkRegistrationReq.java
  src/main/java/com/financial/product/controller/KeywordController.java
Labels: Type: Documentation, Status: Completed, Status: Available

#77 fix: #76 swagger config 추가
  src/main/java/com/financial/global/config/SecurityConfig.java
  src/main/java/com/financial/global/config/SwaggerConfig.java
Labels: Type: Documentation, Status: Completed

#82 #81 [feature] 맞춤상품 목록 조회 api 생성
  src/main/java/com/financial/interest/repository/InterestRepository.java
  src/main/java/com/financial/member/controller/MemberController.java
  src/main/java/com/financial/member/dto/MemberRecommendDTO.java
  src/main/java/com/financial/member/service/MemberService.java
Labels: Type: Maintenance, Status: Completed, Status: Available, Priority: Low, For: Backend, For: API

#85 #84
  src/main/java/com/financial/global/exception/ErrorCode.java
  src/main/java/com/financial/global/exception/GlobalExceptionHandler.java
Labels: Status: Completed, For: Backend, For: API

#106 fix: applyId, bookmarkId 리턴하도록 dto 수정
  src/main/java/com/financial/apply/dto/MemberProductRes.java
Labels: Priority: High, For: API
